name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: angular/package-lock.json
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build
    - name: Emscripten
      run: |
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..
        emcmake cmake -S . -B build_debug -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="" -DCMAKE_BUILD_TYPE="Debug"
        emcmake cmake -S . -B build_release -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="" -DCMAKE_BUILD_TYPE="Release"
        cmake --build build_debug --parallel 4
        cmake --build build_release --parallel 4
    - name: Angular Debug
      run: |
        mkdir angular/src/assets
        cp build_debug/web_* angular/src/assets/
        cd angular
        npm install -g @angular/cli
        npm install
        ng build --configuration development
        cd ..
    - name: Register Debug website in known_hosts
      run: |
        mkdir /home/runner/.ssh
        chmod 700 /home/runner/.ssh
        echo "${{ secrets.UPLOAD_KNOW_HOST }}" >> /home/runner/.ssh/known_hosts
    - name: Upload to Debug website
      run: |
        sshpass -p ${{ secrets.UPLOAD_PASSWORD }} sftp -P ${{ secrets.UPLOAD_PORT }} ${{ secrets.UPLOAD_USERNAME }}@${{ secrets.UPLOAD_HOST }}:${{ secrets.UPLOAD_PATH_DEBUG }} <<EOF
          rm *
          mput angular/dist/web-demangler/browser/*
        bye
        EOF
    - name: Angular Release
      run: |
        rm angular/src/assets/*
        rm -Rf angular/build
        cp build_release/web_* angular/src/assets/
        cd angular
        npm install -g @angular/cli
        npm install
        ng build --configuration production
    - name: Upload to Release website
      run: |
        sshpass -p ${{ secrets.UPLOAD_PASSWORD }} sftp -P ${{ secrets.UPLOAD_PORT }} ${{ secrets.UPLOAD_USERNAME }}@${{ secrets.UPLOAD_HOST }}:${{ secrets.UPLOAD_PATH_RELEASE }} <<EOF
          rm *
          mput angular/dist/web-demangler/browser/*
        bye
        EOF
